reload('andrepatta.plugins-setup')
reload('andrepatta.debugger')
reload('andrepatta.core.colorscheme')
reload('andrepatta.core.dashboard')
reload('andrepatta.core.keymaps')
reload('andrepatta.core.options')
